robot:
  name: 'sea_joint' # [required] less than ROBOT_NAME_MAXLEN(20 bytes)
  #  license: 'FB3B37E5-014B554C-F51CA7DF' # i7 研域工控
  license: '5C82D722-B7ED8BA0-A9CE72C0' # 研华范晓亮的工控机
  #license: '2A183B38-9F93C32D-B25DDBCD' # i5 研域工控
  loop_hz: 1000     # [required] control frequency
  slave_number: 1 # [required]
  slaves:
   - id: 0 # The order of the slave [required]
     name: joint_1
     inputs: # [optional]
       group_name: 'TxPDO Mapping 1'
       status_word: 'Statusword'
       position_actual_value: 'Position actual value'
       velocity_actual_value: 'Velocity actual value'
       torque_actual_value: 'Torque actual value'
       load_torque_value: 'Analog input 1'
       secondary_position_value: 'Secondary position value'
       secondary_velocity_value: 'Secondary velocity value'
     outputs: # [optional]
       group_name: 'RxPDO Mapping 1'
       mode_of_operation: 'Modes of operation'
       control_word: 'Controlword'
       target_position: 'Target position'
       target_velocity: 'Target velocity'
       target_torque: 'Target torque'
