robot:
  name: 'sia_robot' # [required] less than ROBOT_NAME_MAXLEN(20 bytes)
#  license: 'FB3B37E5-014B554C-F51CA7DF'
  license: '5C82D722-B7ED8BA0-A9CE72C0'
  loop_hz: 1000     # [required] control frequency
  slave_number: 4 # [required]
  slaves:
    - id: 0 # The order of the slave [required]
      name: joint_1
      inputs: # [optional]
        status_word: 'Status word'
        position_actual_value: 'Position actual value'
        velocity_actual_value: 'Velocity actual value'
        torque_actual_value: 'Torque actual value'
        load_torque_value: 'Analog Input 1'
      outputs: # [optional]
        mode_of_operation: 'Mode of operation'
        control_word: 'Control word'
        target_position: 'Target Position'
        target_velocity: 'Target Velocity'
        target_torque: 'Target Torque'
    - id: 1 # The order of the slave [required]
      name: joint_2
      inputs: # [optional]
        status_word: 'Status word'
        position_actual_value: 'Position actual value'
        velocity_actual_value: 'Velocity actual value'
        torque_actual_value: 'Torque actual value'
        load_torque_value: 'Analog Input 1'
      outputs: # [optional]
        mode_of_operation: 'Mode of operation'
        control_word: 'Control word'
        target_position: 'Target Position'
        target_velocity: 'Target Velocity'
        target_torque: 'Target Torque'
    - id: 2 # The order of the slave [required]
      name: joint_3
      inputs: # [optional]
        status_word: 'Status word'
        position_actual_value: 'Position actual value'
        velocity_actual_value: 'Velocity actual value'
        torque_actual_value: 'Torque actual value'
        load_torque_value: 'Analog Input 1'
      outputs: # [optional]
        mode_of_operation: 'Mode of operation'
        control_word: 'Control word'
        target_position: 'Target Position'
        target_velocity: 'Target Velocity'
        target_torque: 'Target Torque'
    - id: 3 # The order of the slave [required]
      name: joint_4
      inputs: # [optional]
        status_word: 'Status word'
        position_actual_value: 'Position actual value'
        velocity_actual_value: 'Velocity actual value'
        torque_actual_value: 'Torque actual value'
        load_torque_value: 'Analog Input 1'
      outputs: # [optional]
        mode_of_operation: 'Mode of operation'
        control_word: 'Control word'
        target_position: 'Target Position'
        target_velocity: 'Target Velocity'
        target_torque: 'Target Torque'
