robot:
  name: 'techservo_robot' # [required] less than ROBOT_NAME_MAXLEN(20 bytes)
  #  license: 'FB3B37E5-014B554C-F51CA7DF'
  license: '5C82D722-B7ED8BA0-A9CE72C0'
  loop_hz: 1000     # [required] control frequency
  slave_number: 6 # [required]
  slaves:
    - id: 0 # The order of the slave [required]
      name: joint_1
      inputs: # [optional]
        group_name: 'Transmit PDO 5'
        status_word: 'Status word'
        position_actual_value: 'Actual motor position'
        velocity_actual_value: 'Actual motor velocity'
        torque_actual_value: 'Torque actual value'
      outputs: # [optional]
        group_name: 'Receive PDO 5'
        control_word: 'Control word'
        target_position: 'Profile target position'
    - id: 1 # The order of the slave [required]
      name: joint_2
      inputs: # [optional]
        group_name: 'Transmit PDO 5'
        status_word: 'Status word'
        position_actual_value: 'Actual motor position'
        velocity_actual_value: 'Actual motor velocity'
        torque_actual_value: 'Torque actual value'
      outputs: # [optional]
        group_name: 'Receive PDO 5'
        control_word: 'Control word'
        target_position: 'Profile target position'
    - id: 2 # The order of the slave [required]
      name: joint_3
      inputs: # [optional]
        group_name: 'Transmit PDO 5'
        status_word: 'Status word'
        position_actual_value: 'Actual motor position'
        velocity_actual_value: 'Actual motor velocity'
        torque_actual_value: 'Torque actual value'
      outputs: # [optional]
        group_name: 'Receive PDO 5'
        control_word: 'Control word'
        target_position: 'Profile target position'
    - id: 3 # The order of the slave [required]
      name: joint_4
      inputs: # [optional]
        group_name: 'Transmit PDO 5'
        status_word: 'Status word'
        position_actual_value: 'Actual motor position'
        velocity_actual_value: 'Actual motor velocity'
        torque_actual_value: 'Torque actual value'
      outputs: # [optional]
        group_name: 'Receive PDO 5'
        control_word: 'Control word'
        target_position: 'Profile target position'
    - id: 4 # The order of the slave [required]
      name: joint_5
      inputs: # [optional]
        group_name: 'Transmit PDO 5'
        status_word: 'Status word'
        position_actual_value: 'Actual motor position'
        velocity_actual_value: 'Actual motor velocity'
        torque_actual_value: 'Torque actual value'
      outputs: # [optional]
        group_name: 'Receive PDO 5'
        control_word: 'Control word'
        target_position: 'Profile target position'
    - id: 5 # The order of the slave [required]
      name: joint_6
      inputs: # [optional]
        group_name: 'Transmit PDO 5'
        status_word: 'Status word'
        position_actual_value: 'Actual motor position'
        velocity_actual_value: 'Actual motor velocity'
        torque_actual_value: 'Torque actual value'
      outputs: # [optional]
        group_name: 'Receive PDO 5'
        control_word: 'Control word'
        target_position: 'Profile target position'

#    - id: 0 # The order of the slave [required]
#      name: joint_1
#      inputs: # [optional]
#        status_word: 'Status word'
#        position_actual_value: 'Position actual value'
#        velocity_actual_value: 'Velocity actual value'
#        torque_actual_value: 'Torque actual value'
#        load_torque_value: 'Analog Input 1'
#      outputs: # [optional]
#        mode_of_operation: 'Mode of operation'
#        control_word: 'Control word'
#        target_position: 'Target Position'
#        target_velocity: 'Target Velocity'
#        target_torque: 'Target Torque'
#    - id: 1 # The order of the slave [required]
#      name: joint_2
#      inputs: # [optional]
#        status_word: 'Status word'
#        position_actual_value: 'Position actual value'
#        velocity_actual_value: 'Velocity actual value'
#        torque_actual_value: 'Torque actual value'
#        load_torque_value: 'Analog Input 1'
#      outputs: # [optional]
#        mode_of_operation: 'Mode of operation'
#        control_word: 'Control word'
#        target_position: 'Target Position'
#        target_velocity: 'Target Velocity'
#        target_torque: 'Target Torque'
#    - id: 2 # The order of the slave [required]
#      name: joint_3
#      inputs: # [optional]
#        status_word: 'Status word'
#        position_actual_value: 'Position actual value'
#        velocity_actual_value: 'Velocity actual value'
#        torque_actual_value: 'Torque actual value'
#        load_torque_value: 'Analog Input 1'
#      outputs: # [optional]
#        mode_of_operation: 'Mode of operation'
#        control_word: 'Control word'
#        target_position: 'Target Position'
#        target_velocity: 'Target Velocity'
#        target_torque: 'Target Torque'
#    - id: 3 # The order of the slave [required]
#      name: joint_4
#      inputs: # [optional]
#        status_word: 'Status word'
#        position_actual_value: 'Position actual value'
#        velocity_actual_value: 'Velocity actual value'
#        torque_actual_value: 'Torque actual value'
#        load_torque_value: 'Analog Input 1'
#      outputs: # [optional]
#        mode_of_operation: 'Mode of operation'
#        control_word: 'Control word'
#        target_position: 'Target Position'
#        target_velocity: 'Target Velocity'
#        target_torque: 'Target Torque'
