robot:
  name: 'sia_robot' # [required] less than ROBOT_NAME_MAXLEN(20 bytes)
  loop_hz: 1000     # [required] control frequency
  number_of_joints: 1 # [required]
  joints:
    - id: 0 # The order of joints [required]
      name: joint_1
      mode_of_operation: csp # csp / csv / cst
      min_position: -1000.00 # rad [required]
      max_position: 1000.00 # rad [required]
      max_velocity: 2.3562 #  rad/s -> radius per second [required]
      max_acceleration: 679.21 # rad/s^2 [required]
      counts_per_round: 524288 #encoder counts per joint round [required]
      torque_range: 100.0 # Nm the Range of the torque sensor
      ec_slave_name: 'Slave_1001 [Elmo Drive ]' # [required]
      inputs: # [optional]
        ec_status_word: 'Status word'
        ec_position_actual_value: 'Position actual value'
        ec_velocity_actual_value: 'Velocity actual value'
        ec_torque_actual_value: 'Torque actual value'
        ec_load_torque_value: 'Analog Input 1'
      outputs: # [optional]
        ec_mode_of_operation: 'Mode of operation'
        ec_control_word: 'Control word'
        ec_target_position: 'Target Position'
        ec_target_velocity: 'Target Velocity'
        ec_target_torque: 'Target Torque'


